=== Sandr0x00/recipes/schema.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "id": "/All",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string",
            "required": true,
            "minLength": 3
        },
        "name": {
            "type": "string",
            "required": true,
            "minLength": 3
        },
        "headless": {
            "type": "boolean"
        },
        "portions": {
            "type": "string",
            "pattern": "^[0-9].*"
        },
        "images": {
            "type": "array",
            "required": true,
            "uniqueItems": true
        },
        "tags": {
            "type": "array",
            "required": true,
            "uniqueItems": true,
            "minItems": 1,
            "items": {
                "type": "string",
                "pattern": "^[a-z-]+$",
                "required": true,
                "minLength": 2
            }
        },
        "ingredients": {
            "type": "object",
            "required": true,
            "minProperties": 1,
            "additionalProperties": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "amount": {
                        "type": "string",
                        "pattern": "^([0-9]+(g|ml| TL| EL| Pkg.)|\\+)?"
                    },
                    "name": {
                        "type": "string",
                        "required": true,
                        "minLength": 2
                    },
                    "link": {
                        "type": "string"
                    }
                }
            }
        },
        "preparation": {
            "required": true,
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                    "type": "string",
                    "required": true,
                    "minLength": 2
                }
        },
        "garnish": {
            "type": "string",
            "required": false
        },
        "utensils": {
            "type": "string",
            "required": false
        },
        "link": {
            "type": "array"
        },
        "original": {
            "type": "string",
            "required": false
        }
    }
}

=== Sandr0x00/recipes/recipes/dumpling-dough.json
{
    "name": "Dumpling Teig",
    "headless": true,
    "tags": [
        "ingredient",
        "pasta",
        "asian"
    ],
    "ingredients": {
        "mehl": {
            "amount": "300g"
        },
        "wasser": {
            "amount": "150g"
        },
        "salz": {
        }
    },
    "preparation": [
        "{salz} in kochendem {wasser} auflösen. Mit {mehl} vermischen.",
        "Mit einer Pastamschine dünn ausrollen.",
        "Kreise ausstechen."
    ]
}

=== Sandr0x00/recipes/recipes/gluehweinkirschen.json
{
    "name": "Glühweinkirschen",
    "portions": "5 Portionen",
    "tags": [
        "christmas",
        "sweet",
        "pot"
    ],
    "ingredients": {
        "kirschen": {
            "amount": "1 Glas (720ml)"
        },
        "wein-rot": {
            "amount": "350ml"
        },
        "zimtstange": {
            "amount": "1"
        },
        "zitrone": {
            "amount": "Abrieb einer"
        },
        "orange": {
            "amount": "Abrieb einer"
        },
        "staerke": {
            "amount": "1 TL"
        }
    },
    "preparation": [
        "{kirschen} abseihen.",
        "{wein-rot} mit {zitrone} und {orange} sowie {zimtstange} 5 Minuten köcheln lassen.",
        "{staerke} mit den zwei Esslöffeln Rotwein glatt rühren und unter Rühren zur Weinmischung geben. Die Mischung aufkochen lassen und so lange kochen lassen, bis sie leicht angedickt ist.",
        "Die Kirschen hinzugeben und erwärmen."
    ],
    "original": "https://www.kleineskulinarium.de/2018/12/zimt-panna-cotta-mit-gluehweinkirschen/"
}

=== Sandr0x00/recipes/recipes/kuerbispueree.json
{
    "name": "Kürbis&shy;püree",
    "tags": [
        "main",
        "pot",
        "side",
        "vegi"
    ],
    "ingredients": {
        "kuerbis": {
            "amount": "1"
        },
        "zwiebel": {
            "amount": "1"
        },
        "knoblauchzehe": {
            "amount": "2"
        },
        "creme-fraiche": {},
        "oel": {},
        "wein-weiss": {},
        "salz-pfeffer": {}
    },
    "preparation": [
        "{kuerbis} schälen und das Fruchtfleisch in Würfel schneiden. {zwiebel} und {knoblauchzehe} schälen, hacken und in {oel} anschwitzen.",
        "Kürbis dazu, kurz mit angeschwitzen und mit {wein-weiss} ablöschen und ca. 15 Minuten zudecken und weiterkochen.",
        "Sieben und die Flüssigkeit auffangen.",
        "Das Feste mit dem Stabmixer zusammen mit {creme-fraiche}, {salz-pfeffer} pürieren und die Konsistenz mit der Kochflüssigkeit regulieren."
    ]
}

=== Sandr0x00/recipes/recipes/schoko-muffin.json
{
    "name": "Schoko Muffin",
    "portions": "12 Muffins",
    "tags": [
        "vegi",
        "chocolate",
        "sweet",
        "vegan",
        "oven"
    ],
    "ingredients": {
        "mehl": {
            "amount": "250g"
        },
        "zucker": {
            "amount": "170g"
        },
        "backpulver": {
            "amount": "10g"
        },
        "kakao": {
            "amount": "30g"
        },
        "oel": {
            "amount": "100g"
        },
        "milch-soja": {
            "amount": "250g"
        }
    },
    "preparation": [
        "{mehl}, {zucker}, {kakao}, {backpulver} mit {oel} und {milch-soja} mixen.",
        "Den Teig auf 12 Muffinformen verteilen und 25 Minuten bei 180Â°C backen."
    ]
}

=== Sandr0x00/recipes/recipes/chili-con-potato.json
{
    "name": "Chili con potato",
    "portions": "4 Portionen",
    "tags": [
        "main",
        "mexican",
        "pot",
        "vegi"
    ],
    "ingredients": {
        "kartoffel": {
            "amount": "500g"
        },
        "zwiebel": {
            "amount": "2"
        },
        "knoblauchzehe": {},
        "tomaten-passiert": {
            "amount": "1 Pkg."
        },
        "bier": {
            "amount": "350ml"
        },
        "chili": {},
        "kidneybohnen": {
            "amount": "1 Dose"
        },
        "mais": {
            "amount": "1 Dose"
        },
        "tomatenmark": {
            "amount": "2 EL"
        },
        "gewuerze": {
            "name": "Salz, Pfeffer, Kümmel, Paprikapulver, Thymian, Zucker und Kakaopulver"
        },
        "baguette": {
            "amount": "1"
        },
        "creme-fraiche": {}
    },
    "preparation": [
        "{zwiebel}, {knoblauchzehe} und {kartoffel} würfeln.",
        "{zwiebel} und {knoblauchzehe} anschwitzen. {kartoffel}, {tomatenmark} hinzufügen und mit anschwitzen.",
        "{bier}, {tomaten-passiert}, {chili}, {mais} und {gewuerze} hinzufügen.",
        "{kidneybohnen} hinzufügen und einkochen.",
        "Mit {baguette} und {creme-fraiche} servieren."
    ]
}

=== Sandr0x00/recipes/recipes/kiwi-joghurt-drink.json
{
    "name": "Kiwi Joghurt Drink",
    "tags": [
        "drink",
        "longdrink",
        "blender"
    ],
    "ingredients": {
        "joghurt": {
            "amount": "200g"
        },
        "zucker": {
            "amount": "1 EL"
        },
        "kiwi": {
            "amount": "1"
        },
        "vanilleeis": {
            "amount": "1 Kugel"
        }
    },
    "preparation": [
        "{joghurt}, {zucker} und {kiwi} pürieren/mixen. Mit {vanilleeis} ins Glas geben."
    ],
    "garnish": "Kiwischeiben/-stückchen"
}

=== Sandr0x00/recipes/recipes/pasta.json
{
    "name": "Pasta",
    "tags": [
        "pasta",
        "italian",
        "ingredient",
        "vegi",
        "side"
    ],
    "ingredients": {
        "mehl": {
            "amount": "200g"
        },
        "ei": {
            "amount": "2"
        },
        "salz": {}
    },
    "preparation": [
        "{salz} und {mehl} vermischen. Eine Mulde in {mehl} machen und die {ei} hinein geben.",
        "Den Teig kneten bis er glatt wird (dauert ein bisschen).",
        "Den Teig für 30 Minuten in Frischhaltefolie einwickeln und bei Zimmertemparatur ruhen lassen.",
        "Ein paar mal durch die gröbste Stufe der Pastamaschine rollen. Dabei immer wieder zusammenfalten bis der Teig nicht mehr reißt.",
        "Mit der Pastamaschine bis zur gewünschten Dicke ausrollen."
    ],
    "original": "https://www.springlane.de/magazin/rezeptideen/lasagne-selber-machen/"
}

=== Sandr0x00/recipes/recipes/kohlrouladen.json
{
    "name": "Kohlrouladen",
    "tags": [
        "meat",
        "main",
        "oven",
        "lowcarb"
    ],
    "ingredients": {
        "hackfleisch": {
            "amount": "500g"
        },
        "ei": {
            "amount": "1"
        },
        "semmel": {
            "amount": "1"
        },
        "senf-dijon": {
            "amount": "1 EL"
        },
        "zwiebel": {
            "amount": "1"
        },
        "weisskohl": {
            "amount": "1/2"
        },
        "speck": {
            "amount": "100g Würfel"
        },
        "bruehe": {
            "amount": "500ml"
        },
        "sahne": {
            "amount": "200ml"
        },
        "paprikapulver": {},
        "salz-pfeffer": {}
    },
    "preparation": [
        "Acht {weisskohl} Blätter blanchieren. In Eiswasser abschrecken und trocknen.",
        "{semmel} schredderbn, einweichen und ausdrücken. {zwiebel} fein würfeln.",
        "{hackfleisch}, {ei}, Semmel, {senf-dijon}, die Zwiebel, {paprikapulver}, {salz-pfeffer} in eine Schüssel geben und vermengen.",
        "Hackfleischteig in Kohlblätter geben, zusammenrollen und mit einem Küchengarn zusammenbinden.",
        "Die Kohlrouladen in einer hohen Pfanne mit {speck} anbraten, sodass sie Farbe bekommen. Haben die Kohlrouladen etwas Farbe angenommen, mit {bruehe} aufgießen. Zugedeckt ca. 30 Minuten schmoren lassen.",
        "Die Rouladen herausnehmen. {sahne} zur Soße geben, etwas einkochen lassen. Mit {salz-pfeffer} abschmecken."
    ],
    "original": "https://www.chefkoch.de/rezepte/426431133556910/Omas-Kohlrouladen.html"
}
