=== Sandr0x00/recipes/schema.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "id": "/All",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string",
            "required": true,
            "minLength": 3
        },
        "name": {
            "type": "string",
            "required": true,
            "minLength": 3
        },
        "headless": {
            "type": "boolean"
        },
        "portions": {
            "type": "string",
            "pattern": "^[0-9].*"
        },
        "images": {
            "type": "array",
            "required": true,
            "uniqueItems": true
        },
        "tags": {
            "type": "array",
            "required": true,
            "uniqueItems": true,
            "minItems": 1,
            "items": {
                "type": "string",
                "pattern": "^[a-z-]+$",
                "required": true,
                "minLength": 2
            }
        },
        "ingredients": {
            "type": "object",
            "required": true,
            "minProperties": 1,
            "additionalProperties": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "amount": {
                        "type": "string",
                        "pattern": "^([0-9]+(g|ml| TL| EL| Pkg.)|\\+)?"
                    },
                    "name": {
                        "type": "string",
                        "required": true,
                        "minLength": 2
                    },
                    "link": {
                        "type": "string"
                    }
                }
            }
        },
        "preparation": {
            "required": true,
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                    "type": "string",
                    "required": true,
                    "minLength": 2
                }
        },
        "garnish": {
            "type": "string",
            "required": false
        },
        "utensils": {
            "type": "string",
            "required": false
        },
        "link": {
            "type": "array"
        },
        "original": {
            "type": "string",
            "required": false
        }
    }
}

=== Sandr0x00/recipes/recipes/spaghetti-carbonara.json
{
    "name": "Spaghetti Carbonara",
    "tags": [
        "pasta",
        "main",
        "pot",
        "pan"
    ],
    "ingredients": {
        "pasta": {},
        "ei": {
            "amount": "2"
        },
        "parmesan": {},
        "pancetta": {
            "name": "Pancetta (Schinken)"
        },
        "pfeffer": {}
    },
    "preparation": [
        "{pasta} kochen. {pancetta} in der Pfanne anbraten.",
        "{ei} mit {parmesan} und {pfeffer} verrühren.",
        "{pasta} zu {pancetta} geben. Von der Hitze nehmen und Ei-Gemisch hinzufügen und verrühren bis die Konsistenz passt."
    ]
}

=== Sandr0x00/recipes/recipes/haselnusskuchen.json
{
    "name": "Haselnusskuchen",
    "tags": [
        "sweet",
        "vegi"
    ],
    "ingredients": {
        "ei": {
            "amount": "5"
        },
        "zucker": {
            "amount": "1/2 Tasse"
        },
        "oel": {
            "amount": "1 Tasse"
        },
        "mehl": {
            "amount": "1 Tasse"
        },
        "haselnuss": {
            "amount": "200g"
        },
        "schokiz": {
            "amount": "150g"
        }
    },
    "preparation": [
        "Tassenangabe: Es ist ein normaler Kaffeepott mit ca. 250 ml Fassungsvermögen gemeint.",
        "Die {ei} schaumig schlagen. Nacheinander {zucker}, {oel}, {mehl} und gemahlene {haselnuss} dazugeben.",
        "Die {schokiz} grob in kleine Stückchen zerhacken und dem Teig unterrühren.",
        "Den Teig in eine Form füllen.",
        "Auf der mittleren Schiene bei 180°C ca. 45 - 55 Minuten backen."
    ]
}

=== Sandr0x00/recipes/recipes/kartoffelsuppe.json
{
    "name": "Kartoffel&shy;suppe",
    "portions": "4 Portionen",
    "tags": [
        "soup",
        "vegi",
        "side",
        "main",
        "pot",
        "dach"
    ],
    "ingredients": {
        "karotte": {
            "amount": "1"
        },
        "kartoffel": {
            "amount": "300g"
        },
        "sellerie": {
            "amount": "150g"
        },
        "paprika": {
            "amount": "1/2"
        },
        "lauchzwiebel": {
            "amount": "1 Bund"
        },
        "wasser": {
            "amount": "500ml"
        },
        "butter": {},
        "zwiebel": {
            "amount": "1/2"
        },
        "bruehe": {},
        "creme-fraiche": {
            "amount": "75g"
        },
        "gewuerze": {
            "name": "Pfeffer und Muskatnuss"
        }
    },
    "preparation": [
        "{kartoffel:100g}, {sellerie} schälen und wie {paprika} und {karotte} würfeln. Die grüne Seite der {lauchzwiebel} in Ringe schneiden.",
        "In {wasser} mit Salz garen. Das Gemüse abgießen und dabei das Kochwasser auffangen. Die Zwiebel und den weißen Teil der Lauchzwiebel fein schneiden.",
        "In dem Topf {butter} schmelzen und die {zwiebel} glasig dünsten. Die restlichen {kartoffel:200g} schälen und in Stücke schneiden. Zusammen mit dem aufgefangenen Kochwasser und der {bruehe} in den Topf geben. Bei geschlossenem Deckel die Kartoffeln gar kochen.",
        "{creme-fraiche}, {gewuerze} hinzugeben und pürieren."
    ],
    "garnish": "gegarten Gemüsewürfeln und Kräutern"
}

=== Sandr0x00/recipes/recipes/sauce-bechamel.json
{
    "name": "Béchamelsauce",
    "tags": [
        "vegi",
        "ingredient",
        "side",
        "sauce",
        "pot"
    ],
    "ingredients": {
        "mehl": {
            "amount": "50g"
        },
        "milch": {
            "amount": "800ml"
        },
        "butter": {
            "amount": "50g"
        },
        "muskat": {},
        "salz-pfeffer": {}
    },
    "preparation": [
        "{butter} schmelzen. {mehl} bei geringer Hitze dazugeben.",
        "Stetig mit einem Schneebesen rühren und 1-2 Minuten anschwitzen, bis eine glatte Masse entstanden ist.",
        "{milch} unter stegigem rühren nach und nach dazu geben. Jeweils, wenn die Masse glatt und klumpenfrei gerührt ist. Sauce ca. 15 Minuten köcheln und andicken lassen. Mit {muskat}, {salz-pfeffer} abschmecken."
    ],
    "original": "https://www.springlane.de/magazin/rezeptideen/lasagne-selber-machen/"
}

=== Sandr0x00/recipes/recipes/trileche.json
{
    "name": "Trileche",
    "portions": "2 Portionen",
    "tags": [
        "sweet",
        "vegi"
    ],
    "ingredients": {
        "ei": {
            "amount": "6"
        },
        "zucker": {
            "amount": "200g"
        },
        "salz": {
            "amount": "3g"
        },
        "backpulver": {
            "amount": "7g"
        },
        "mehl": {
            "amount": "225g"
        },
        "milch": {
            "amount": "120ml"
        },
        "sahne": {
            "amount": "240ml"
        },
        "kondensmilch": {
            "amount": "340g",
            "name": "Kondensmilch 10% (gesüßt)"
        },
        "kaffeesahne": {
            "amount": "400ml",
            "name": "Kaffeesahne 10%"
        },
        "dulce-de-leche": {}
    },
    "preparation": [
        "{ei} teilen. Eigelb mit {zucker:150g} schaumig schlagen. {milch} hinzufügen. Eiweiß mit {zucker:50g} steif schlagen und die andere Eimasse unterheben.",
        "{mehl} mit {backpulver} und {salz} vermischen, ebenfalls unterheben. Form einfetten und Teig hinein geben. Bei 180°C ca. 30 Minuten backen.",
        "{sahne:120ml}, {kondensmilch} und {kaffeesahne} vermischen. Den Kuchen einstechen und die \"Leches\" darüber schütten. Über Nacht zugedeckt einziehen lassen.",
        "Mit {dulce-de-leche} und Sahne ({sahne:120ml} mit einem TL Zucker aufschlagen) bestreichen."
    ],
    "garnish": "Erdbeeren"
}

=== Sandr0x00/recipes/recipes/beeren-smoothie.json
{
    "name": "Beeren Smoothie",
    "tags": [
        "drink",
        "cream",
        "fruity",
        "blender"
    ],
    "ingredients": {
        "banane": {
            "amount": "1"
        },
        "ananassaft": {
            "amount": "170g"
        },
        "heidelbeeren": {
            "amount": "170g"
        },
        "himbeeren": {
            "amount": "170g"
        },
        "honig": {
            "amount": "2 TL"
        },
        "eiswuerfel": {}
    },
    "preparation": [
        "{banane}, {ananassaft}, {heidelbeeren}, {himbeeren}, {honig} mit {eiswuerfel} mixen."
    ]
}

=== Sandr0x00/recipes/recipes/kuerbissuppe.json
{
    "name": "Kürbis&shy;suppe",
    "tags": [
        "soup",
        "main",
        "pot",
        "side",
        "vegi"
    ],
    "portions": "6 Schüssel",
    "ingredients": {
        "kuerbis": {
            "amount": "1"
        },
        "kartoffel": {
            "amount": "200g"
        },
        "zwiebel": {
            "amount": "2"
        },
        "bruehe": {
            "amount": "800ml"
        },
        "sahne": {
            "amount": "200g"
        },
        "butter": {},
        "mehl": {
            "amount": "2 EL"
        },
        "muskat": {},
        "salz-pfeffer": {}
    },
    "preparation": [
        "{kartoffel} schälen und würfeln. {kuerbis} entkernen und in Stücke schneiden. {zwiebel} schälen und würfeln.",
        "{butter} in einem großen Topf erhitzen. {zwiebel} glasig dünsten. {kuerbis} und {kartoffel} kurz mitdünsten. {mehl} darüberstäuben und anschwitzen.",
        "{bruehe} und {sahne} hinzu gießen und zugedeckt bei schwacher Hitze ca. 25 Minuten köcheln lassen.",
        "Pürieren und mit {muskat}, {salz-pfeffer} abschmecken."
    ],
    "garnish": "Crème fraîche, Kürbiskernöl oder Kürbiskernen"
}

=== Sandr0x00/recipes/recipes/butterschmalz.json
{
    "name": "Butter&shy;schmalz",
    "tags": [
        "ingredient"
    ],
    "ingredients": {
        "butter": {
            "amount": "250g"
        }
    },
    "preparation": [
        "{butter} würfeln und auf kleinster Stufe langsam schmelzen und köcheln lassen (die Butter darf nicht zu hoch erhitzt werden).",
        "Mit der Zeit setzt sich das Eiweis unten ab und das Wasser verdampft.",
        "Den Schaum, der sich oben bildet abschöpfen. Sobald das komplette Wasser verdampft ist und sich das komplette Eiweis am Topfboden abgesetzt hat, die geklärte Butter durch ein Tuch sieben.",
        "Im Kühlschrank bis zu einem Jahr haltbar."
    ]
}
