=== Sandr0x00/recipes/schema.json
{
    "$schema": "http://json-schema.org/draft/2019-09/schema#",
    "id": "/All",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "id": {
            "type": "string",
            "required": true,
            "minLength": 3
        },
        "name": {
            "type": "string",
            "required": true,
            "minLength": 3
        },
        "headless": {
            "type": "boolean"
        },
        "portions": {
            "type": "string",
            "pattern": "^[0-9].*"
        },
        "images": {
            "type": "array",
            "required": true,
            "uniqueItems": true
        },
        "tags": {
            "type": "array",
            "required": true,
            "uniqueItems": true,
            "minItems": 1,
            "items": {
                "type": "string",
                "pattern": "^[a-z-]+$",
                "required": true,
                "minLength": 2
            }
        },
        "ingredients": {
            "type": "object",
            "required": true,
            "minProperties": 1,
            "additionalProperties": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "amount": {
                        "type": "string",
                        "pattern": "^([0-9]+(g|ml| TL| EL| Pkg.)|\\+)?"
                    },
                    "name": {
                        "type": "string",
                        "required": true,
                        "minLength": 2
                    },
                    "link": {
                        "type": "string"
                    }
                }
            }
        },
        "preparation": {
            "required": true,
                "type": "array",
                "uniqueItems": true,
                "minItems": 1,
                "items": {
                    "type": "string",
                    "required": true,
                    "minLength": 2
                }
        },
        "garnish": {
            "type": "string",
            "required": false
        },
        "utensils": {
            "type": "string",
            "required": false
        },
        "link": {
            "type": "array"
        },
        "original": {
            "type": "string",
            "required": false
        }
    }
}

=== Sandr0x00/recipes/recipes/whisky-sauce.json
{
    "name": "Whisky Soße",
    "tags": [
        "sauce",
        "pot"
    ],
    "ingredients": {
        "butter": {},
        "zwiebel": {
            "amount": "1"
        },
        "knoblauchzehe": {
            "amount": "1"
        },
        "ketchup": {
            "amount": "5 EL"
        },
        "sirup-zucker": {
            "amount": "5 EL",
            "link": "sirup-zucker"
        },
        "whisky": {
            "amount": "4 EL"
        },
        "essig-balsamico": {
            "amount": "1 EL"
        }
    },
    "preparation": [
        "{butter} in einem Topf bei mittlerer Hitze zerlassen.",
        "{zwiebel} unter rühren goldbraun braten. {knoblauchzehe} hinzufügen und mitbraten.",
        "{ketchup}, {sirup-zucker}, {whisky}, {essig-balsamico} hinzufügen. 10 - 15min köcheln lassen."
    ]
}

=== Sandr0x00/recipes/recipes/pina-colada.json
{
    "name": "Pina Colada",
    "tags": [
        "drink",
        "alcohol",
        "hurricane",
        "blender"
    ],
    "ingredients": {
        "rum-weiss": {
            "amount": "5cl"
        },
        "ananassaft": {
            "amount": "5cl"
        },
        "kokosmilch": {
            "amount": "5cl"
        },
        "ananas": {
            "amount": "1 Scheibe"
        }
    },
    "preparation": [
        "{ananassaft}, {rum-weiss}, {kokosmilch} und {ananas} mit 3 bis 4 Eisw√ºrfeln mixen.",
        "Ins Glas geben."
    ],
    "garnish": "Ananasscheibe"
}

=== Sandr0x00/recipes/recipes/panna-cotta-zimt.json
{
    "name": "Zimt Panna Cotta",
    "portions": "5 Portionen",
    "tags": [
        "christmas",
        "sweet",
        "pot"
    ],
    "ingredients": {
        "sahne": {
            "amount": "550g"
        },
        "zucker": {
            "amount": "50g"
        },
        "zimtstange": {
            "amount": "1"
        },
        "zimt": {
            "amount": "1/2 TL"
        },
        "gelatine": {
            "amount": "4 Blatt"
        }
    },
    "preparation": [
        "{gelatine} in kaltem Wasser einweichen.",
        "{sahne} mit {zucker}, {zimtstange} und {zimt} in einen Topf geben und unter Rühren erhitzen. Ein Mal aufkochen lassen und dann einige Minuten bei mittlerer Stufe ziehen lassen. Dann durch ein feines Sieb in eine Schüssel abseihen.",
        "Gelatine ausdrücken und unter Rühren zur heißen Sahnemischung geben.",
        "Die Panna Cotta in Förmchen geben und im Kühlschrank einige Stunden fest werden lassen."
    ],
    "original": "https://www.kleineskulinarium.de/2018/12/zimt-panna-cotta-mit-gluehweinkirschen/"
}

=== Sandr0x00/recipes/recipes/brioche-bun.json
{
    "name": "Brioche Brötchen",
    "portions": "6 Buns",
    "tags": [
        "side",
        "oven",
        "vegi",
        "ingredient",
        "burger"
    ],
    "ingredients": {
        "tangzhong": {
            "link": "/tangzhong"
        },
        "milch": {
            "amount": "120g"
        },
        "hefe": {
            "amount": "9g"
        },
        "mehl": {
            "amount": "420g"
        },
        "salz": {
            "amount": "7g"
        },
        "zucker": {
            "amount": "35g"
        },
        "ei": {
            "amount": "3"
        },
        "butter": {
            "amount": "40g"
        }
    },
    "preparation": [
        "{milch} erwärmen und mit {hefe} 10 Minuten auflösen lassen.",
        "{tangzhong}, {mehl}, {salz}, {zucker}, {butter} mit {milch} und {ei:2} zusammengeben und zu einem Teig kneten. 1.5h in einer eingefetteten Schüssel gehen lassen.",
        "In 100g schwere Bällchen teilen. Den Teig auseinander ziehen und oben zusammenfalten. Dann umdrehen und die Öffnung schließen. Die Bällchen eine Stunde gehen lassen.",
        "{ei:1} mit einem Schuss {milch} vermischen und damit die Bällchen bestreichen. Bei 180°C für 15min goldbraun backen."
    ]
}

=== Sandr0x00/recipes/recipes/tzatziki.json
{
    "name": "Tzatziki",
    "tags": [
        "side",
        "ingredient",
        "pan",
        "balkan"
    ],
    "ingredients": {
        "joghurt-greek": {
            "amount": "500g"
        },
        "gurke": {
            "amount": "1/2"
        },
        "knoblauchzehe": {
            "amount": "4"
        },
        "lemon-preserved": {
            "amount": "1/4"
        },
        "petersilie": {
        }
    },
    "preparation": [
        "{gurke} klein schneiden. {knoblauchzehe}, {lemon-preserved} und {petersilie} klein hacken.",
        "{joghurt-greek} mit den anderen Zutaten mischen."
    ]
}

=== Sandr0x00/recipes/recipes/leberknoedelsuppe.json
{
    "name": "Leberknödelsuppe",
    "tags": [
        "soup",
        "meat",
        "main"
    ],
    "ingredients": {
        "leber": {
            "amount": "120g"
        },
        "wasser": {},
        "knoblauchzehe": {
            "amount": "1"
        },
        "semmel": {
            "amount": "2"
        },
        "semmelbroesel": {
            "amount": "50g"
        },
        "ei": {
            "amount": "1"
        },
        "zwiebel": {
            "amount": "1/2"
        },
        "salz-pfeffer": {},
        "petersilie": {},
        "majoran": {},
        "butter": {}
    },
    "preparation": [
        "{leber} durch einen Fleischwolf drehen.",
        "{semmel} in {wasser} einweichen und anschließend gut ausdrücken. {zwiebel} in sehr feine Würfel schneiden. {knoblauchzehe} pressen und {petersilie} fein hacken.",
        "{zwiebel}, {knoblauchzehe}, {petersilie} und {majoran} in {butter} anschwitzen. Anschließend alles erkalten lassen.",
        "Semmel, Leber, Zwiebelgemisch, {ei}, {semmelbroesel}, {salz-pfeffer} gut verrühren und für 5 Minuten rasten lassen.",
        "Mit feuchten Händen Leberknödel formen und in die kochende Suppe geben und für 20-25 Minuten bei kleiner Flamme darin ziehen lassen."
    ]
}

=== Sandr0x00/recipes/recipes/erdbeerlimes.json
{
    "name": "Erdbeer&shy;limes",
    "portions": "4 Liter",
    "tags": [
        "drink",
        "alcohol",
        "fruity",
        "pot",
        "blender"
    ],
    "ingredients": {
        "erdbeeren": {
            "amount": "1kg"
        },
        "limettensaft": {
            "amount": "350ml"
        },
        "zucker": {
            "amount": "200g"
        },
        "wodka": {
            "amount": "500ml"
        },
        "wasser": {
            "amount": "200ml"
        }
    },
    "preparation": [
        "{wasser} mit {zucker} kurz aufkochen. {erdbeeren} mixen und zusammen mit {limettensaft} und {wodka} zum Zuckerwasser geben."
    ]
}

=== Sandr0x00/recipes/recipes/schweinefilet-rosenkohl.json
{
    "name": "Schweinefilet auf Rosenkohl",
    "tags": [
        "meat",
        "main",
        "oven",
        "pan",
        "dach"
    ],
    "ingredients": {
        "rosenkohl": {
            "amount": "1"
        },
        "kartoffel": {
            "amount": "500g"
        },
        "knoblauchzehe": {
            "amount": "2"
        },
        "rosmarin": {},
        "kuemmel": {},
        "salz": {},
        "oel": {},
        "schweinefilet": {
            "amount": "500g"
        },
        "pfeffer": {},
        "quark-kraeuter": {}
    },
    "preparation": [
        "{kartoffel} in Spalten schneiden. {knoblauchzehe} zerdr체cken. {knoblauchzehe}, {kartoffel}, {rosenkohl}, {rosmarin}, {kuemmel}, {salz}, {pfeffer} mit {oel} mischen.",
        "Im Ofen bei 180째C f체r ca. 30 Minuten backen.",
        "{schweinefilet} trocken tupfen und in {oel} scharf anbraten. Mit in den Ofen geben und 10 Minuten mitgaren. 5 Minuten abk체hlen lassen.",
        "Mit {quark-kraeuter} servieren."
    ],
    "garnish": "Erdbeere"
}
